freebsd_instance:
  image: freebsd-12-0-release-amd64
task:
  name: FreeBSD
  env:
    matrix:
      - JULIA_VERSION: 1.0
        env: JULIA_CUBA_BUILD_SOURCE=false
      - JULIA_VERSION: 1.0
        env: JULIA_CUBA_BUILD_SOURCE=true
      - JULIA_VERSION: 1.1
        env: JULIA_CUBA_BUILD_SOURCE=false
      - JULIA_VERSION: 1.1
        env: JULIA_CUBA_BUILD_SOURCE=true
      - JULIA_VERSION: 1.2
        env: JULIA_CUBA_BUILD_SOURCE=false
      - JULIA_VERSION: 1.2
        env: JULIA_CUBA_BUILD_SOURCE=true
      - JULIA_VERSION: 1.3
        env: JULIA_CUBA_BUILD_SOURCE=false
      - JULIA_VERSION: 1.3
        env: JULIA_CUBA_BUILD_SOURCE=true
      - JULIA_VERSION: nightly
        env: JULIA_CUBA_BUILD_SOURCE=false
      - JULIA_VERSION: nightly
        env: JULIA_CUBA_BUILD_SOURCE=true
  allow_failures: $JULIA_VERSION == "nightly"
  install_script:
    - sh -c "$(fetch https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh -o -)"
  build_script:
    - julia --project=. --check-bounds=yes --color=yes -e 'using Pkg; pkg"add https://github.com/staticfloat/Cairo.jl#sf/jll_packages"'
    - cirrusjl build
  test_script:
    - cirrusjl test
  coverage_script:
    - cirrusjl coverage codecov coveralls
